export const GET_REQUEST_PRODUCT = "GET_REQUEST_PRODUCT"
export const GET_SUCCESS_PRODCUT = "GET_SUCCESS_PRODUCT"
export const GET_FAIL_PRODUCT = "GET_FAIL_PRODUCT"

export const GET_REQUEST_TOKEN = "GET_REQUEST_TOKEN"
export const GET_SUCCESS_TOKEN = "GET_SUCCESS_TOKEN"
export const GET_FAIL_TOKEN = "GET_FAIL_TOKEN"

export const GET_SUCCESS_SINGLE="GET_SUCCESS_SINGLE"